import{i as h,a as b,S as L}from"./assets/vendor-bad0427b.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const e={searchForm:document.getElementById("searchForm"),galleryImages:document.querySelector("ul.gallery"),loader:document.querySelector(".loader"),loadBtn:document.querySelector(".load-btn")},n={perPage:40,page:1,query:"",maxPage:0},c="is-hidden";e.loader.style.display="none";e.searchForm.addEventListener("submit",q);e.loadBtn.addEventListener("click",g);async function q(t){t.preventDefault(),e.galleryImages.innerHTML="";const a=t.currentTarget;if(n.query=a.elements.searchQuery.value.trim(),!!n.query){n.page=1,e.loader.style.display="block";try{const{hits:s,totalHits:l}=await d(n);n.maxPage=Math.ceil(l/n.perPage),s.length>0&&s.length!==l?(e.loadBtn.classList.remove(c),m(s,e.galleryImages)):(e.loadBtn.classList.add(c),h.show({message:"❌Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#EF4040",position:"topRight",maxWidth:"420px",close:!1}),e.galleryImages.innerHTML="")}catch(s){u(s)}finally{a.reset()}}}function d({query:t,page:a=1,perPage:s}){return b.get("https://pixabay.com/api/?key=41802498-7aef04e1b4b4791f33c618bc1",{params:{q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,perPage:s,page:a}}).then(({data:l})=>l)}async function g(){n.page+=1,e.loader.style.display="none",e.loadBtn.disablet=!0;try{const{hits:t}=await d(n);m(t,e.galleryImages)}catch(t){u(t)}finally{e.loader.style.display="none",e.loadBtn.disablet=!1}n.page===n.maxPage&&(e.loadBtn.classList.add(c),e.loader.style.display="none",e.loadBtn.removeEventListener("click",g))}function m(t){const a=t.map(({webformatURL:l,largeImageURL:r,tags:o,likes:i,views:f,comments:y,downloads:p})=>`
 <li class="gallery-item">
 <a class="link-gallery" href="${r}">
 <img class="gallery-images" src="${l}" alt="${o}">
 </a>
 <div class="photo-info">
     <p class="info-number"><strong>Like</strong> ${i}</p>
     <p class="info-number"><strong>Views</strong> ${f}</p>
     <p class="info-number"><strong>Comments</strong> ${y}</p>
     <p class="info-number"><strong>Downloads</strong> ${p}</p> 
 </div>
 </li>
`).join("");e.galleryImages.insertAdjacentHTML("beforeend",a),new L(document.querySelectorAll(".gallery a")).refresh()}function u(t){console.log(t),e.loader.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
